version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: galery_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: galery_db
    ports:
      - "5435:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: